; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Dingo! - narzędzie do grafików pracy"
#define MyAppVersion "1.2.0"
#define MyAppPublisher "Kewin Madej"
#define MyAppURL "https://www.madebykewin.pl"
#define MyAppExeName "Dingo! - narzędzie do grafików pracy.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B346C64A-AA7F-4BE8-8938-C5A62A795EDF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\Dingo\Dingo!
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
CloseApplications=yes
CloseApplicationsFilter={#MyAppExeName}
RestartApplications=yes
; Instalator pisze do {localappdata} (per-user), ale przy PrivilegesRequired=admin
; elevacja moze zajsc na innym koncie administratora niz zalogowany uzytkownik -
; wtedy {localappdata} wskazuje na profil TEGO admina, a nie uzytkownika programu,
; wiec aktualizacja instaluje sie w innym miejscu i skrot dalej wskazuje na stara wersje.
PrivilegesRequired=lowest
OutputBaseFilename=DingoSetup
SetupIconFile=C:\Users\kewi1\Desktop\madebykewin\Grafik dino V2\dingo_icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\kewi1\Desktop\madebykewin\Grafik dino V2\dist\Dingo! - narzędzie do grafików pracy\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Znaczniki "widziano samouczek" (np. CONFIG_TUTORIAL_FLAG w
; ui/config_dialog.py, LOCATIONS_TUTORIAL_FLAG itd.) - aplikacja tworzy je
; przy pierwszym uruchomieniu w SWOIM WŁASNYM katalogu roboczym ({app}, bo
; skróty w [Icons] nie ustawiają WorkingDir - patrz też "last_project.json").
; Domyślny deinstalator kasuje tylko pliki wpisane w [Files], więc bez tego
; te znaczniki zostałyby osierocone po odinstalowaniu - przy ponownej
; instalacji samouczki "pamiętałyby" (błędnie), że użytkownik już je widział.
Type: files; Name: "{app}\*.flag"

