from pathlib import Path
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from logic.schedule_controller import ScheduleController
from model.employee import Employee
from model.month_schedule import MonthSchedule
from model.shop_config import ShopConfig


def _make_controller():
    emp = Employee(last_name="Kowalski", first_name="Jan")
    schedule = MonthSchedule(2026, 9, employees=[emp])
    shop = ShopConfig(2026, 9)
    controller = ScheduleController(schedule, shop)
    return controller, emp


class SetDayPresetTests(unittest.TestCase):
    """set_day_preset (Konfiguracja -> "Ustawienia trybu szybkiego"):
    zastosowanie ręcznie zdefiniowanego przedziału na komórce grafiku,
    zamiennik ręcznego wpisywania godzin przyciskiem "Praca"."""

    def test_normal_preset_sets_hours_and_locks_the_cell(self):
        controller, emp = _make_controller()
        preset = {"name": "Zmiana 16h", "start": "06:00", "end": "22:00", "full_day": False}

        controller.set_day_preset(emp, 1, preset)

        ds = controller.get_day(emp, 1)
        self.assertEqual(ds.start, "06:00")
        self.assertEqual(ds.end, "22:00")
        self.assertFalse(ds.is_full_day)
        self.assertTrue(ds.is_locked)

    def test_overnight_preset_sets_hours_crossing_midnight(self):
        controller, emp = _make_controller()
        preset = {"name": "Nocka", "start": "22:00", "end": "06:00", "full_day": False}

        controller.set_day_preset(emp, 1, preset)

        ds = controller.get_day(emp, 1)
        self.assertEqual((ds.start, ds.end), ("22:00", "06:00"))
        self.assertTrue(ds.crosses_midnight())

    def test_full_day_preset_uses_set_full_day_shift(self):
        controller, emp = _make_controller()
        preset = {"name": "Doba 24h", "start": "06:00", "end": None, "full_day": True}

        controller.set_day_preset(emp, 1, preset)

        ds = controller.get_day(emp, 1)
        self.assertEqual(ds.start, "06:00")
        self.assertEqual(ds.end, "06:00")
        self.assertTrue(ds.is_full_day)
        self.assertEqual(ds.total_duration().total_seconds(), 24 * 3600)

    def test_reapplying_the_same_preset_is_a_noop_for_history(self):
        controller, emp = _make_controller()
        preset = {"name": "Zmiana 16h", "start": "06:00", "end": "22:00", "full_day": False}

        controller.set_day_preset(emp, 1, preset)
        history_len = len(controller.history)

        controller.set_day_preset(emp, 1, preset)

        self.assertEqual(len(controller.history), history_len)

    def test_applying_a_preset_locks_the_cell_even_if_hours_already_match(self):
        # Regression: a cell can already show the same hours "by coincidence"
        # (e.g. auto-generated by the solver) without being manually locked.
        # Clicking the matching preset must still lock it, not silently no-op.
        controller, emp = _make_controller()
        ds = controller.get_day(emp, 1)
        ds.set_hours("06:00", "22:00")
        self.assertFalse(ds.is_locked)

        controller.set_day_preset(emp, 1, {"name": "Zmiana 16h", "start": "06:00", "end": "22:00", "full_day": False})

        ds = controller.get_day(emp, 1)
        self.assertTrue(ds.is_locked)

    def test_switching_from_full_day_to_normal_preset_updates_the_cell(self):
        controller, emp = _make_controller()
        controller.set_day_preset(emp, 1, {"name": "Doba 24h", "start": "06:00", "end": None, "full_day": True})

        controller.set_day_preset(emp, 1, {"name": "Zmiana 16h", "start": "06:00", "end": "22:00", "full_day": False})

        ds = controller.get_day(emp, 1)
        self.assertFalse(ds.is_full_day)
        self.assertEqual(ds.end, "22:00")

    def test_preset_bypasses_the_single_night_shift_config_check(self):
        # set_day_hours()/set_shift() reject end<=start unless it matches
        # shop_config's single night_shift - set_day_preset must not inherit
        # that restriction, since the preset itself is already validated.
        controller, emp = _make_controller()
        preset = {"name": "Nocka 23-05", "start": "23:00", "end": "05:00", "full_day": False}

        controller.set_day_preset(emp, 1, preset)

        ds = controller.get_day(emp, 1)
        self.assertEqual((ds.start, ds.end), ("23:00", "05:00"))


if __name__ == "__main__":
    unittest.main()
